"""Closed Product A vocabulary; these values define no transition or policy engine."""

from enum import StrEnum


class InvocationType(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"


class RunType(StrEnum):
    PREMARKET = "PREMARKET"


class ExecutionStatus(StrEnum):
    CREATED = "CREATED"
    COLLECTING = "COLLECTING"
    NORMALIZING = "NORMALIZING"
    ANALYZING = "ANALYZING"
    AWAITING_SYNTHESIS = "AWAITING_SYNTHESIS"
    VALIDATING = "VALIDATING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class DataQualityStatus(StrEnum):
    PASS = "PASS"
    DEGRADED = "DEGRADED"
    FAIL = "FAIL"


class DeliveryStatus(StrEnum):
    ON_TIME = "ON_TIME"
    DELAYED = "DELAYED"
    MANUAL = "MANUAL"
    MISSED_WINDOW = "MISSED_WINDOW"


class Capability(StrEnum):
    MARKET_SUMMARY_AVAILABLE = "MARKET_SUMMARY_AVAILABLE"
    REGIME_CLASSIFICATION_AVAILABLE = "REGIME_CLASSIFICATION_AVAILABLE"
    WATCHLIST_METRICS_AVAILABLE = "WATCHLIST_METRICS_AVAILABLE"
    EVENT_RISK_CHECK_AVAILABLE = "EVENT_RISK_CHECK_AVAILABLE"
    SETUP_DETECTION_AVAILABLE = "SETUP_DETECTION_AVAILABLE"
    PLAN_DRAFT_AVAILABLE = "PLAN_DRAFT_AVAILABLE"
    POSITION_SIZING_AVAILABLE = "POSITION_SIZING_AVAILABLE"
    PORTFOLIO_HEAT_CHECK_AVAILABLE = "PORTFOLIO_HEAT_CHECK_AVAILABLE"


class Session(StrEnum):
    PRE_MARKET = "PRE_MARKET"
    REGULAR = "REGULAR"
    POST_MARKET = "POST_MARKET"
    COMPLETED_SESSION = "COMPLETED_SESSION"


class Coverage(StrEnum):
    SINGLE_EXCHANGE = "single_exchange"
    CONSOLIDATED = "consolidated"
    UNKNOWN = "unknown"


class ClaimType(StrEnum):
    FACT = "FACT"
    CALCULATION = "CALCULATION"
    INFERENCE = "INFERENCE"
    HYPOTHESIS = "HYPOTHESIS"


class BriefOrigin(StrEnum):
    SYNTHESIZED = "SYNTHESIZED"
    DETERMINISTIC_REDUCED = "DETERMINISTIC_REDUCED"
    OPERATIONAL = "OPERATIONAL"


class ReportSection(StrEnum):
    RUN_STATUS = "Run Status"
    MARKET_POSTURE = "Market Posture"
    WHAT_CHANGED = "What Changed"
    TODAY_EVENT_CLOCK = "Today’s Event Clock"
    CORE_MARKET_RISKS = "Core Market Risks"
    WATCHLIST_PRIORITIES = "Watchlist Priorities"
    EXECUTIVE_TRADE_PLAN_DRAFTS = "Trade Plan Drafts"
    DATA_WARNINGS = "Data Warnings"
    MARKET_REGIME = "Market Regime"
    MACRO_EVENT_CALENDAR = "Macro and Event Calendar"
    BROAD_MARKET_RADAR = "Broad-Market Radar"
    SECTOR_ROTATION = "Sector Rotation"
    CROSS_ASSET_RISK_SIGNALS = "Cross-Asset Risk Signals"
    CORE_MONITOR = "Core Monitor"
    WATCHLIST_DASHBOARD = "Watchlist Dashboard"
    ELIGIBLE_SETUPS = "Eligible Setups"
    DETAILED_TRADE_PLAN_DRAFTS = "Trade Plan Drafts"
    BLOCKED_EXCLUDED_CANDIDATES = "Blocked and Excluded Candidates"
    CHANGES_SINCE_PRIOR_RUN = "Changes Since Prior Run"
    DATA_QUALITY_LIMITATIONS = "Data Quality and Limitations"
    EVIDENCE_INDEX = "Evidence Index"
    METHODOLOGY_RISK_NOTICE = "Methodology and Risk Notice"


class ValidationSeverity(StrEnum):
    ERROR = "ERROR"
    WARNING = "WARNING"


class ValidationCode(StrEnum):
    SCHEMA_INVALID = "SCHEMA_INVALID"
    RUN_ID_MISMATCH = "RUN_ID_MISMATCH"
    REQUIRED_SECTION_MISSING = "REQUIRED_SECTION_MISSING"
    REQUIRED_SECTION_ORDER = "REQUIRED_SECTION_ORDER"
    INVALID_PLAN_STATE = "INVALID_PLAN_STATE"
    INVALID_CAPABILITY_STATE = "INVALID_CAPABILITY_STATE"
    DETERMINISTIC_VALUE_MISMATCH = "DETERMINISTIC_VALUE_MISMATCH"
    IRRELEVANT_CITATION = "IRRELEVANT_CITATION"
    COUNTER_EVIDENCE_OMITTED = "COUNTER_EVIDENCE_OMITTED"
    STATUS_OVERCLAIM = "STATUS_OVERCLAIM"
    IEX_COVERAGE_OVERCLAIM = "IEX_COVERAGE_OVERCLAIM"
    DISABLED_CAPABILITY_OMITTED = "DISABLED_CAPABILITY_OMITTED"
    IMPERATIVE_TRADING_LANGUAGE = "IMPERATIVE_TRADING_LANGUAGE"
    BLOCKED_PLAN_OVERCLAIM = "BLOCKED_PLAN_OVERCLAIM"
    UNSUPPORTED_SIZING_VALUE = "UNSUPPORTED_SIZING_VALUE"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    CLAIM_REACHABILITY = "CLAIM_REACHABILITY"
    EXPIRY_INVALIDATION_MISSING = "EXPIRY_INVALIDATION_MISSING"
    TEXT_LIMIT_EXCEEDED = "TEXT_LIMIT_EXCEEDED"
    UNKNOWN_EVIDENCE = "UNKNOWN_EVIDENCE"
    UNKNOWN_METRIC = "UNKNOWN_METRIC"


class SynthesisSection(StrEnum):
    EXECUTIVE = "EXECUTIVE"
    DETAILED = "DETAILED"


class GateStatus(StrEnum):
    PASS = "PASS"
    WARNING = "WARNING"
    BLOCK = "BLOCK"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"


class ObservationOutcome(StrEnum):
    ENTRY_ZONE_NOT_OBSERVED = "ENTRY_ZONE_NOT_OBSERVED"
    ENTRY_ZONE_OBSERVED = "ENTRY_ZONE_OBSERVED"
    INVALIDATION_OBSERVED = "INVALIDATION_OBSERVED"
    TARGET_OBSERVED = "TARGET_OBSERVED"
    AMBIGUOUS_SEQUENCE = "AMBIGUOUS_SEQUENCE"
    OBSERVATION_WINDOW_ENDED = "OBSERVATION_WINDOW_ENDED"
