"""Closed Product A vocabulary; these values define no transition or policy engine."""

from enum import StrEnum


class InvocationType(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"


class RunType(StrEnum):
    PREMARKET = "PREMARKET"


class ExecutionStatus(StrEnum):
    CREATED = "CREATED"
    COLLECTING = "COLLECTING"
    NORMALIZING = "NORMALIZING"
    ANALYZING = "ANALYZING"
    AWAITING_SYNTHESIS = "AWAITING_SYNTHESIS"
    VALIDATING = "VALIDATING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class DataQualityStatus(StrEnum):
    PASS = "PASS"
    DEGRADED = "DEGRADED"
    FAIL = "FAIL"


class DeliveryStatus(StrEnum):
    ON_TIME = "ON_TIME"
    DELAYED = "DELAYED"
    MANUAL = "MANUAL"
    MISSED_WINDOW = "MISSED_WINDOW"


class Capability(StrEnum):
    MARKET_SUMMARY_AVAILABLE = "MARKET_SUMMARY_AVAILABLE"
    REGIME_CLASSIFICATION_AVAILABLE = "REGIME_CLASSIFICATION_AVAILABLE"
    WATCHLIST_METRICS_AVAILABLE = "WATCHLIST_METRICS_AVAILABLE"
    EVENT_RISK_CHECK_AVAILABLE = "EVENT_RISK_CHECK_AVAILABLE"
    SETUP_DETECTION_AVAILABLE = "SETUP_DETECTION_AVAILABLE"
    PLAN_DRAFT_AVAILABLE = "PLAN_DRAFT_AVAILABLE"
    POSITION_SIZING_AVAILABLE = "POSITION_SIZING_AVAILABLE"
    PORTFOLIO_HEAT_CHECK_AVAILABLE = "PORTFOLIO_HEAT_CHECK_AVAILABLE"


class Session(StrEnum):
    PRE_MARKET = "PRE_MARKET"
    REGULAR = "REGULAR"
    POST_MARKET = "POST_MARKET"
    COMPLETED_SESSION = "COMPLETED_SESSION"


class Coverage(StrEnum):
    SINGLE_EXCHANGE = "single_exchange"
    CONSOLIDATED = "consolidated"
    UNKNOWN = "unknown"


class ClaimType(StrEnum):
    FACT = "FACT"
    CALCULATION = "CALCULATION"
    INFERENCE = "INFERENCE"
    HYPOTHESIS = "HYPOTHESIS"


class GateStatus(StrEnum):
    PASS = "PASS"
    WARNING = "WARNING"
    BLOCK = "BLOCK"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"


class ObservationOutcome(StrEnum):
    ENTRY_ZONE_NOT_OBSERVED = "ENTRY_ZONE_NOT_OBSERVED"
    ENTRY_ZONE_OBSERVED = "ENTRY_ZONE_OBSERVED"
    INVALIDATION_OBSERVED = "INVALIDATION_OBSERVED"
    TARGET_OBSERVED = "TARGET_OBSERVED"
    AMBIGUOUS_SEQUENCE = "AMBIGUOUS_SEQUENCE"
    OBSERVATION_WINDOW_ENDED = "OBSERVATION_WINDOW_ENDED"
