"""Stable Product A failure vocabulary, independent of provider exception types."""

from enum import StrEnum


class ErrorCode(StrEnum):
    CONFIGURATION_INVALID = "CONFIGURATION_INVALID"
    CREDENTIALS_MISSING = "CREDENTIALS_MISSING"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    MARKET_CALENDAR_UNAVAILABLE = "MARKET_CALENDAR_UNAVAILABLE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_SCHEMA_DRIFT = "PROVIDER_SCHEMA_DRIFT"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    INVALID_REQUEST = "INVALID_REQUEST"
    EVIDENCE_CUTOFF_VIOLATION = "EVIDENCE_CUTOFF_VIOLATION"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    STALE_DATA = "STALE_DATA"
    UNSUPPORTED_INSTRUMENT = "UNSUPPORTED_INSTRUMENT"
    SIZING_UNAVAILABLE = "SIZING_UNAVAILABLE"
    PORTFOLIO_HEAT_UNAVAILABLE = "PORTFOLIO_HEAT_UNAVAILABLE"
    INVALID_RUN_STATE = "INVALID_RUN_STATE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    PUBLICATION_FAILED = "PUBLICATION_FAILED"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
